// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRecipes.Persistence.Context;

#nullable disable

namespace MyRecipes.Persistence.Migrations
{
    [DbContext(typeof(MyRecipeDbContext))]
    partial class MyRecipeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyRecipes.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef34d609-1f2d-4863-ab67-1dc4dd822333"),
                            Index = 0,
                            Name = "Hlavné jedlá",
                            Picture = "",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("05457a86-e2b0-4b5c-90d4-9fb657b10449"),
                            Index = 1,
                            Name = "Polievky a prílohy",
                            Picture = "",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("ae3289c8-3ad3-48e8-9ed3-b3ece7be5c03"),
                            Index = 2,
                            Name = "Raňajky a večere",
                            Picture = "",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("ed101e92-c1d3-494e-824f-f208af796cfd"),
                            Index = 3,
                            Name = "Sladké a slané",
                            Picture = "",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("6d4ca1ca-bba5-45f3-890f-2ffcdf400bb8"),
                            Index = 4,
                            Name = "Sviatočné jedlá",
                            Picture = "",
                            Visibility = true
                        },
                        new
                        {
                            Id = new Guid("77bd497a-9a8c-40e1-aec5-a03d82292e10"),
                            Index = 5,
                            Name = "Všetky recepty",
                            Picture = "",
                            Visibility = true
                        });
                });

            modelBuilder.Entity("MyRecipes.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfServings")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<string>("Process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("MyRecipes.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
